FROM node:17-alpine as builder
WORKDIR /app
COPY package.json .
RUN npm install 
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
COPY . .

RUN npm run build

# Path: client\dockerfile
FROM nginx:1.21.3-alpine
WORKDIR  /usr/share/nginx/html
COPY --from=builder /app/build .

# Path: client\dockerfile
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]   

